app:
  cloud:
    ums:
      url: 127.0.0.1:8083
  # 开启延迟任务
  delayqueue:
    enableConsume: true #是否开启延迟队列的消费任 务
    enableScheduleTask: true #是否开启延迟队列的调 度任务
    enableScheduleRetryFailTask: true #是否开启对于失 败任务进行重试的调度任务
  union:
    search:
      enable: true
      knowledgeSource: 3522367790851822463
  appCode: fs-user-sys-1641545626689
  projectCode: fs-user-project-1641547050881
  orgType: administration
  mq:
    producer:
      type: rocket #消息插件类型(我们用roketMQ)
      rocket: #生产者配置
        topic: knowledge_gather
        namesrvAddr: 10.254.99.78:9876 #mq测试环境服务器地址
        groupName: video-server #组名
  pbs:
    client:
      #url: http://10.7.211.36:6253/
      url: http://127.0.0.1:6300/    #本地登录
  gwapi:
    name: server
    url: http://10.7.211.201:5001/
  rpc:
    accessKey: f16f9f26940523ee
    accessSecret: ddc88eb541f7a4bb
    signVersion: V1
  customParams:
    organUrl: http://119.188.115.249:5001%s/api/queryDynamicTree # http://60.208.61.171:82%s/api/queryOrgTree # 查询组织 /api/receive/baidu/gwapi/jxk
    userUrl: http://119.188.115.249:5001%s/api/contracts # 查询目录
    rootCityCode: '10112__01' # 山东地市编码
    projectRoleCode: fs-user-role-1642038967224
    superRoleCode: fs-user-role-1641547328061
    appId: 3496254400060468410
    appCode: fosung_workbeach
  globalParams:
    loginUrl: /login
    logoutUrl: /logout
    registerUrl: /api/common/register
    resetPwdUrl: /api/common/reset/password
    ossUrl : http://119.188.115.252:8090/api/oss/resource-handle/upload
    umsUrl: http://10.7.211.201:5001
  dao:
    dataSource:
      driverClass: com.highgo.jdbc.Driver
      password: root
      url: jdbc:highgo://127.0.0.1:5432/fosung_workbench?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
      username: postgres
    jpa:
      showSql: true
  secure:
    auth:
      enable: true
      urlAuths:
        - filter: anon
          url: /login,/logout,/api/common/register,/api/common/reset/password,/api/common/photo/code,/api/**
    referer:
      enable: false
    sso:
      enable: false
      oauth2Configs:
        - authorizationUri: http://10.254.23.23:8922/sso/oauth/authorize
          clientAuthenticationMethod: basic
          clientId: party-branch-ui #cloud-gateway #dp_center_ui
          clientName: 网关管理端
          clientSecret: cloud-gateway #dp_center_ui
          frontPageUrl: http://127.0.0.1:9528
          registrationId: dt
          scope: edu.read
          redirectUriTemplate: http://129.0.0.1:9005/oauth2/login
          tokenUri: http://10.254.23.23:8922/sso/oauth/token
          userInfoUri: http://10.254.23.23:8922/sso/user/principal
  session:
    cookieSessionEncode: true
spring:
  redis:
    database: '8'
    host: 127.0.0.1
    port: '6379'
server:
  port: 8082
  connection-timeout: 18000000
  #servlet:
    #session:
      #timeout: 30

### feign中启用熔断隔离 配置
feign:
  hystrix:
    enabled: true
logging:
  level:
    com.fosung.workbench.dao: DEBUG
