app:
  code: fs-user-sys-1640066493611
  dao:
    dataSource:
      driverClass: com.highgo.jdbc.Driver
      password: 123qwe
      url: jdbc:highgo://10.7.201.181:5432/fosung_system-v2?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
      username: postgres
    jpa:
      showSql: 'true'
  faceUsers: http://t-gw-proxy.xczx-jn.com/cloud_meeting/meeting/out/faceUsers
  globalParams:
    loginUrl: /toLogin
    logoutUrl: /logout
    ossUrl: http://119.188.115.252:8090/api/oss/resource-handle/upload
  secure:
    auth:
      enable: 'true'
      login-page-redirect-url: http://127.0.0.1:8080/oauth2/login/system
      urlAuths:
        - filter: logineduser
          url: /**
    referer:
      enable: 'false'
    sso:
      enable: 'true'
      oauth2Configs:
        - authorizationUri: http://10.7.211.29:8100/oauth/authorize
          clientAuthenticationMethod: basic
          clientId: system
          clientName: system
          clientSecret: system
          frontPageUrl: http://127.0.0.1:8080/api/getTest?id=1&name=2
          redirectUriTemplate: http://127.0.0.1:8080/oauth2/login
          registrationId: system
          scope: login
          tokenUri: http://10.7.211.29:8100/oauth/token
          userInfoUri: http://10.7.211.29:8100/oauth/userinfo
  session:
    cookieSessionEncode: 'false'
spring:
  redis:
    database: '10'
    host: 10.7.211.101
    password: 1qaz@wsx?Z
    port: '19000'